version: '3.5'

services:
  backend:
    image: backend-project
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
  frontend:
    image: frontend-project
    ports:
      - 5000:5000
  redis:
    image: redis

# The backend and frontend images are from the earlier exercises in the part 1. 
