version: '3.5'

services:
  backend:
    image: backend-project
    ports:
      - 8080:8080
  frontend:
    image: frontend-project
    ports:
      - 5000:5000

# The images are from the earlier exercises in the part 1. 
# They worked right out the box.
