version: '3.5'

services:
  backend:
    build: ./backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
  frontend:
    build: ./frontend
    ports:
      - 5000:5000
  redis:
    image: redis

